import type { Hotel, Staff, Room, Reservation, Guest, DashboardStats } from "./types"

// Mock Hotels
export const MOCK_HOTELS: Hotel[] = [
  {
    id: "hotel-1",
    name: "Grand Hotel",
    address: "123 Main Street",
    city: "New York",
    country: "USA",
    phone: "+1 234 567 8900",
    email: "info@grandhotel.com",
    modules: ["front-office", "point-of-sale", "housekeeping", "accounts", "reports"],
    status: "active",
    createdAt: "2024-01-15",
    roomCount: 150,
  },
  {
    id: "hotel-2",
    name: "Seaside Resort",
    address: "456 Beach Road",
    city: "Miami",
    country: "USA",
    phone: "+1 234 567 8901",
    email: "info@seasideresort.com",
    modules: ["front-office", "point-of-sale", "housekeeping"],
    status: "active",
    createdAt: "2024-02-20",
    roomCount: 200,
  },
  {
    id: "hotel-3",
    name: "Mountain Lodge",
    address: "789 Highland Ave",
    city: "Denver",
    country: "USA",
    phone: "+1 234 567 8902",
    email: "info@mountainlodge.com",
    modules: ["front-office", "housekeeping"],
    status: "pending",
    createdAt: "2024-03-10",
    roomCount: 75,
  },
  {
    id: "hotel-4",
    name: "City Center Inn",
    address: "321 Downtown Blvd",
    city: "Chicago",
    country: "USA",
    phone: "+1 234 567 8903",
    email: "info@citycenterinn.com",
    modules: ["front-office", "accounts"],
    status: "inactive",
    createdAt: "2024-01-05",
    roomCount: 100,
  },
]

// Mock Staff for Grand Hotel
export const MOCK_STAFF: Staff[] = [
  {
    id: "staff-1",
    name: "John Manager",
    email: "admin@grandhotel.com",
    role: "admin",
    hotelId: "hotel-1",
    modules: ["front-office", "point-of-sale", "housekeeping", "accounts", "reports"],
    status: "active",
    createdAt: "2024-01-15",
    lastLogin: "2024-12-20",
  },
  {
    id: "staff-2",
    name: "Sarah Receptionist",
    email: "sarah@grandhotel.com",
    role: "staff",
    hotelId: "hotel-1",
    modules: ["front-office"],
    status: "active",
    createdAt: "2024-02-01",
    lastLogin: "2024-12-19",
  },
  {
    id: "staff-3",
    name: "Mike Accountant",
    email: "mike@grandhotel.com",
    role: "staff",
    hotelId: "hotel-1",
    modules: ["accounts", "reports"],
    status: "active",
    createdAt: "2024-02-15",
    lastLogin: "2024-12-18",
  },
  {
    id: "staff-4",
    name: "Lisa Housekeeping",
    email: "lisa@grandhotel.com",
    role: "staff",
    hotelId: "hotel-1",
    modules: ["housekeeping"],
    status: "inactive",
    createdAt: "2024-03-01",
  },
]

// Mock Rooms for Grand Hotel
export const MOCK_ROOMS: Room[] = [
  { id: "room-1", number: "101", floor: 1, type: "standard", status: "available", price: 100, amenities: ["WiFi", "TV", "AC"] },
  { id: "room-2", number: "102", floor: 1, type: "standard", status: "occupied", price: 100, amenities: ["WiFi", "TV", "AC"], guestName: "James Wilson", checkIn: "2024-12-18", checkOut: "2024-12-22" },
  { id: "room-3", number: "103", floor: 1, type: "deluxe", status: "occupied", price: 150, amenities: ["WiFi", "TV", "AC", "Mini Bar"], guestName: "Emma Davis", checkIn: "2024-12-19", checkOut: "2024-12-23" },
  { id: "room-4", number: "104", floor: 1, type: "standard", status: "cleaning", price: 100, amenities: ["WiFi", "TV", "AC"] },
  { id: "room-5", number: "201", floor: 2, type: "deluxe", status: "available", price: 150, amenities: ["WiFi", "TV", "AC", "Mini Bar"] },
  { id: "room-6", number: "202", floor: 2, type: "deluxe", status: "reserved", price: 150, amenities: ["WiFi", "TV", "AC", "Mini Bar"], guestName: "Robert Brown", checkIn: "2024-12-21", checkOut: "2024-12-25" },
  { id: "room-7", number: "203", floor: 2, type: "suite", status: "occupied", price: 250, amenities: ["WiFi", "TV", "AC", "Mini Bar", "Jacuzzi"], guestName: "Olivia Martinez", checkIn: "2024-12-17", checkOut: "2024-12-24" },
  { id: "room-8", number: "204", floor: 2, type: "standard", status: "maintenance", price: 100, amenities: ["WiFi", "TV", "AC"] },
  { id: "room-9", number: "301", floor: 3, type: "suite", status: "available", price: 250, amenities: ["WiFi", "TV", "AC", "Mini Bar", "Jacuzzi"] },
  { id: "room-10", number: "302", floor: 3, type: "presidential", status: "available", price: 500, amenities: ["WiFi", "TV", "AC", "Mini Bar", "Jacuzzi", "Kitchen", "Living Room"] },
  { id: "room-11", number: "303", floor: 3, type: "suite", status: "occupied", price: 250, amenities: ["WiFi", "TV", "AC", "Mini Bar", "Jacuzzi"], guestName: "Michael Johnson", checkIn: "2024-12-20", checkOut: "2024-12-22" },
  { id: "room-12", number: "304", floor: 3, type: "deluxe", status: "available", price: 150, amenities: ["WiFi", "TV", "AC", "Mini Bar"] },
]

// Mock Reservations
export const MOCK_RESERVATIONS: Reservation[] = [
  {
    id: "res-1",
    reservationId: "RES-001",
    guestName: "James Wilson",
    guestEmail: "james@email.com",
    guestPhone: "+1 555 0101",
    roomId: "room-2",
    roomNumber: "102",
    checkIn: "2024-12-18",
    checkOut: "2024-12-22",
    status: "checked-in",
    totalAmount: 400,
    paidAmount: 400,
    createdAt: "2024-12-10",
  },
  {
    id: "res-2",
    reservationId: "RES-002",
    guestName: "Emma Davis",
    guestEmail: "emma@email.com",
    guestPhone: "+1 555 0102",
    roomId: "room-3",
    roomNumber: "103",
    checkIn: "2024-12-19",
    checkOut: "2024-12-23",
    status: "checked-in",
    totalAmount: 600,
    paidAmount: 300,
    createdAt: "2024-12-12",
  },
  {
    id: "res-3",
    reservationId: "RES-003",
    guestName: "Robert Brown",
    guestEmail: "robert@email.com",
    guestPhone: "+1 555 0103",
    roomId: "room-6",
    roomNumber: "202",
    checkIn: "2024-12-21",
    checkOut: "2024-12-25",
    status: "confirmed",
    totalAmount: 600,
    paidAmount: 600,
    createdAt: "2024-12-15",
  },
  {
    id: "res-4",
    reservationId: "RES-004",
    guestName: "Olivia Martinez",
    guestEmail: "olivia@email.com",
    guestPhone: "+1 555 0104",
    roomId: "room-7",
    roomNumber: "203",
    checkIn: "2024-12-17",
    checkOut: "2024-12-24",
    status: "checked-in",
    totalAmount: 1750,
    paidAmount: 1000,
    createdAt: "2024-12-08",
  },
  {
    id: "res-5",
    reservationId: "RES-005",
    guestName: "Michael Johnson",
    guestEmail: "michael@email.com",
    guestPhone: "+1 555 0105",
    roomId: "room-11",
    roomNumber: "303",
    checkIn: "2024-12-20",
    checkOut: "2024-12-22",
    status: "checked-in",
    totalAmount: 500,
    paidAmount: 500,
    createdAt: "2024-12-18",
  },
]

// Mock Guests
export const MOCK_GUESTS: Guest[] = [
  {
    id: "guest-1",
    name: "James Wilson",
    email: "james@email.com",
    phone: "+1 555 0101",
    idType: "Passport",
    idNumber: "AB123456",
    address: "123 Oak Street, Boston, MA",
    nationality: "American",
    visits: 5,
    totalSpent: 2500,
  },
  {
    id: "guest-2",
    name: "Emma Davis",
    email: "emma@email.com",
    phone: "+1 555 0102",
    idType: "Driver License",
    idNumber: "DL789012",
    address: "456 Pine Ave, San Francisco, CA",
    nationality: "American",
    visits: 3,
    totalSpent: 1800,
  },
  {
    id: "guest-3",
    name: "Robert Brown",
    email: "robert@email.com",
    phone: "+1 555 0103",
    idType: "Passport",
    idNumber: "CD345678",
    address: "789 Maple Blvd, Seattle, WA",
    nationality: "Canadian",
    visits: 2,
    totalSpent: 1200,
  },
  {
    id: "guest-4",
    name: "Olivia Martinez",
    email: "olivia@email.com",
    phone: "+1 555 0104",
    idType: "Passport",
    idNumber: "EF901234",
    address: "321 Cedar Lane, Austin, TX",
    nationality: "Mexican",
    visits: 8,
    totalSpent: 5600,
  },
  {
    id: "guest-5",
    name: "Michael Johnson",
    email: "michael@email.com",
    phone: "+1 555 0105",
    idType: "National ID",
    idNumber: "GH567890",
    address: "654 Birch Road, Phoenix, AZ",
    nationality: "American",
    visits: 1,
    totalSpent: 500,
  },
]

// Mock Dashboard Stats
export const MOCK_DASHBOARD_STATS: DashboardStats = {
  totalRooms: 12,
  occupiedRooms: 5,
  availableRooms: 5,
  todayCheckIns: 2,
  todayCheckOuts: 1,
  revenue: 12450,
  occupancyRate: 42,
}
